export const schoolCourses: {
  [x: string]: { courses: string[]; sessions: string[] };
} = {
  "gh media school": {
    courses: [
      "JOURNALISM AND MEDIA STUDIES",
      "JOURNALISM AND MEDIA ARTS",
      "TV AND FILM PRODUCTION",
      "MULTIMEDIA PRODUCTION",
    ],
    sessions: [
      "CERTIFICATE (1 YEAR)",
      "ADVANCE DIPLOMA (2 YEARS)",
      "CTVET DIPLOMA (2 YEARS)",
    ],
  },
  "gh fashion school": {
    sessions: ["MORNING 8-12", "AFTERNOON 1-5"],
    courses: [
      "CERTIFICATE IN FASHION DESIGN & TECHNOLOGY - 1 YEAR",
      "ADVANCE CERTIFICATE IN FASHION DESIGN & TECHNOLOGY - 2 YEARS",
      "CTVET DIPLOMA (2 YEARS)",
    ],
  },
  "gh cosmetology school": {
    sessions: ["MORNING 8-12", "AFTERNOON 12-4"],
    courses: [
      "CERTIFICATE OF COMPETENCE (1 YEAR)",
      "ADVANCE CERTIFICATE IN COSMETOLOGY (2 YEARS)",
      "CTVET DIPLOMA (2 YEARS)",
    ],
  },
  "gh catering school": {
    sessions: ["MORNING 8-12", "AFTERNOON 1-5"],
    courses: [
      "CERTIFICATE IN CATERING (1 YEAR)",
      "ADVANCED CERTIFICATE IN CATERING (2 YEARS)",
      "CTVET DIPLOMA (2 YEARS)",
    ],
  },
  "gh technology school": {
    courses: ["COMPUTER SYSTEMS"],
    sessions: [
      "CERTIFICATE (1 YEAR)",
      "ADVANCE CERTIFICATE (2 YEARS)",
      "CTVET DIPLOMA (2 YEARS)",
    ],
  },
};

export const NATIONS: {
  id?: string;
  name: string;
  value: string;
  nationality_type: string;
  telcode: string;
}[] = [
  {
    name: "Ghana",
    value: "ghanaian",
    nationality_type: "ghanaian",
    telcode: "+233",
  },
  {
    name: "Nigeria",
    value: "nigerian",
    nationality_type: "nigerian",
    telcode: "+234",
  },
  {
    name: "Afghanista",
    value: "afghan",
    nationality_type: "afghan",
    telcode: "+234",
  },
  {
    name: "Albania",
    value: "albanian",
    nationality_type: "albanian",
    telcode: "+234",
  },
  {
    name: "Algeria",
    value: "algerian",
    nationality_type: "algerian",
    telcode: "+234",
  },
  {
    name: "America",
    value: "american",
    nationality_type: "american",
    telcode: "+1",
  },
  {
    name: "Andorran",
    value: "andorran",
    nationality_type: "andorran",
    telcode: "+1",
  },
  {
    name: "Angolan",
    value: "angolan",
    nationality_type: "angolan",
    telcode: "+1",
  },
  {
    name: "Anguillan",
    value: "anguillan",
    nationality_type: "anguillan",
    telcode: "+1",
  },
  {
    name: "Argentine",
    value: "argentine",
    nationality_type: "argentine",
    telcode: "+1",
  },
  {
    name: "Armenian",
    value: "armenian",
    nationality_type: "armenian",
    telcode: "+1",
  },
  {
    name: "Australian",
    value: "australian",
    nationality_type: "australian",
    telcode: "+1",
  },
  {
    name: "Austrian",
    value: "austrian",
    nationality_type: "austrian",
    telcode: "+1",
  },
  {
    name: "Azerbaijani",
    value: "azerbaijani",
    nationality_type: "azerbaijani",
    telcode: "+1",
  },
  {
    name: "Bahamian",
    value: "bahamian",
    nationality_type: "bahamian",
    telcode: "+1",
  },
  {
    name: "Bahraini",
    value: "bahraini",
    nationality_type: "bahraini",
    telcode: "+1",
  },
  {
    name: "Bangladeshi",
    value: "bangladeshi",
    nationality_type: "bangladeshi",
    telcode: "+1",
  },
  {
    name: "Barbadian",
    value: "barbadian",
    nationality_type: "barbadian",
    telcode: "+1",
  },
  {
    name: "Belarusian",
    value: "belarusian",
    nationality_type: "belarusian",
    telcode: "+1",
  },
  {
    name: "Belgian",
    value: "belgian",
    nationality_type: "belgian",
    telcode: "+1",
  },
  {
    name: "Belizean",
    value: "belizean",
    nationality_type: "belizean",
    telcode: "+1",
  },
  {
    name: "Beninese",
    value: "beninese",
    nationality_type: "beninese",
    telcode: "+1",
  },
  {
    name: "Bermudian",
    value: "bermudian",
    nationality_type: "bermudian",
    telcode: "+1",
  },
  {
    name: "Bhutanese",
    value: "bhutanese",
    nationality_type: "bhutanese",
    telcode: "+1",
  },
  {
    name: "Bolivian",
    value: "bolivian",
    nationality_type: "bolivian",
    telcode: "+1",
  },
  {
    name: "Botswanan",
    value: "botswanan",
    nationality_type: "botswanan",
    telcode: "+1",
  },
  {
    name: "Brazilian",
    value: "brazilian",
    nationality_type: "brazilian",
    telcode: "+1",
  },
  {
    name: "British",
    value: "british",
    nationality_type: "british",
    telcode: "+1",
  },
  {
    name: "British Virgin Islander",
    value: "british virgin islander",
    nationality_type: "british virgin islander",
    telcode: "+1",
  },
  {
    name: "Bruneian",
    value: "bruneian",
    nationality_type: "bruneian",
    telcode: "+1",
  },
  {
    name: "Bulgarian",
    value: "bulgarian",
    nationality_type: "bulgarian",
    telcode: "+1",
  },
  {
    name: "Burkinan",
    value: "burkinan",
    nationality_type: "burkinan",
    telcode: "+1",
  },
  {
    name: "Burmese",
    value: "burmese",
    nationality_type: "burmese",
    telcode: "+1",
  },
  {
    name: "Burundian",
    value: "burundian",
    nationality_type: "burundian",
    telcode: "+1",
  },
  {
    name: "Cambodian",
    value: "cambodian",
    nationality_type: "cambodian",
    telcode: "+1",
  },
  {
    name: "Cameroonian",
    value: "cameroonian",
    nationality_type: "cameroonian",
    telcode: "+1",
  },
  {
    name: "Canadian",
    value: "canadian",
    nationality_type: "canadian",
    telcode: "+1",
  },
  {
    name: "Cape Verdean",
    value: "cape verdean",
    nationality_type: "cape verdean",
    telcode: "+1",
  },
  {
    name: "Cayman Islander",
    value: "cayman islander",
    nationality_type: "cayman islander",
    telcode: "+1",
  },
  {
    name: "Central African",
    value: "central african",
    nationality_type: "central african",
    telcode: "+1",
  },
  {
    name: "Chadian",
    value: "chadian",
    nationality_type: "chadian",
    telcode: "+1",
  },
  {
    name: "Chilean",
    value: "chilean",
    nationality_type: "chilean",
    telcode: "+1",
  },
  {
    name: "Chinese",
    value: "chinese",
    nationality_type: "chinese",
    telcode: "+1",
  },
  {
    name: "Citizen of Antigua and Barbuda",
    value: "citizen of antigua and barbuda",
    nationality_type: "citizen of antigua and barbuda",
    telcode: "+1",
  },
  {
    name: "Citizen of Bosnia and Herzegovina",
    value: "citizen of bosnia and herzegovina",
    nationality_type: "citizen of bosnia and herzegovina",
    telcode: "+1",
  },
  {
    name: "Citizen of Guinea-Bissau",
    value: "citizen of guinea-bissau",
    nationality_type: "citizen of guinea-bissau",
    telcode: "+1",
  },
  {
    name: "Citizen of Kiribati",
    value: "citizen of kiribati",
    nationality_type: "citizen of kiribati",
    telcode: "+1",
  },
  {
    name: "Citizen of Seychelles",
    value: "citizen of seychelles",
    nationality_type: "citizen of seychelles",
    telcode: "+1",
  },
  {
    name: "Citizen of the Dominican Republic",
    value: "citizen of the dominican republic",
    nationality_type: "citizen of the dominican republic",
    telcode: "+1",
  },
  {
    name: "Citizen of Vanuatu ",
    value: "citizen of vanuatu ",
    nationality_type: "citizen of vanuatu ",
    telcode: "+1",
  },
  {
    name: "Colombian",
    value: "colombian",
    nationality_type: "colombian",
    telcode: "+1",
  },
  {
    name: "Comoran",
    value: "comoran",
    nationality_type: "comoran",
    telcode: "+1",
  },
  {
    name: "Congolese (Congo)",
    value: "congolese (congo)",
    nationality_type: "congolese (congo)",
    telcode: "+1",
  },
  {
    name: "Congolese (DRC)",
    value: "congolese (drc)",
    nationality_type: "congolese (drc)",
    telcode: "+1",
  },
  {
    name: "Cook Islander",
    value: "cook islander",
    nationality_type: "cook islander",
    telcode: "+1",
  },
  {
    name: "Costa Rican",
    value: "costa rican",
    nationality_type: "costa rican",
    telcode: "+1",
  },
  {
    name: "Croatian",
    value: "croatian",
    nationality_type: "croatian",
    telcode: "+1",
  },
  {
    name: "Cuban",
    value: "cuban",
    nationality_type: "cuban",
    telcode: "+1",
  },
  {
    name: "Cymraes",
    value: "cymraes",
    nationality_type: "cymraes",
    telcode: "+1",
  },
  {
    name: "Cymro",
    value: "cymro",
    nationality_type: "cymro",
    telcode: "+1",
  },
  {
    name: "Cypriot",
    value: "cypriot",
    nationality_type: "cypriot",
    telcode: "+1",
  },
  {
    name: "Czech",
    value: "czech",
    nationality_type: "czech",
    telcode: "+1",
  },
  {
    name: "Danish",
    value: "danish",
    nationality_type: "danish",
    telcode: "+1",
  },
  {
    name: "Djiboutian",
    value: "djiboutian",
    nationality_type: "djiboutian",
    telcode: "+1",
  },
  {
    name: "Dominican",
    value: "dominican",
    nationality_type: "dominican",
    telcode: "+1",
  },
  {
    name: "Dutch",
    value: "dutch",
    nationality_type: "dutch",
    telcode: "+1",
  },
  {
    name: "East Timorese",
    value: "east timorese",
    nationality_type: "east timorese",
    telcode: "+1",
  },
  {
    name: "Ecuadorean",
    value: "ecuadorean",
    nationality_type: "ecuadorean",
    telcode: "+1",
  },
  {
    name: "Egyptian",
    value: "egyptian",
    nationality_type: "egyptian",
    telcode: "+1",
  },
  {
    name: "Emirati",
    value: "emirati",
    nationality_type: "emirati",
    telcode: "+1",
  },
  {
    name: "English",
    value: "english",
    nationality_type: "english",
    telcode: "+1",
  },
  {
    name: "Equatorial Guinean",
    value: "equatorial guinean",
    nationality_type: "equatorial guinean",
    telcode: "+1",
  },
  {
    name: "Eritrean",
    value: "eritrean",
    nationality_type: "eritrean",
    telcode: "+1",
  },
  {
    name: "Estonian",
    value: "estonian",
    nationality_type: "estonian",
    telcode: "+1",
  },
  {
    name: "Ethiopian",
    value: "ethiopian",
    nationality_type: "ethiopian",
    telcode: "+1",
  },
  {
    name: "Faroese",
    value: "faroese",
    nationality_type: "faroese",
    telcode: "+1",
  },
  {
    name: "Fijian",
    value: "fijian",
    nationality_type: "fijian",
    telcode: "+1",
  },
  {
    name: "Filipino",
    value: "filipino",
    nationality_type: "filipino",
    telcode: "+1",
  },
  {
    name: "Finnish",
    value: "finnish",
    nationality_type: "finnish",
    telcode: "+1",
  },
  {
    name: "French",
    value: "french",
    nationality_type: "french",
    telcode: "+1",
  },
  {
    name: "Gabonese",
    value: "gabonese",
    nationality_type: "gabonese",
    telcode: "+1",
  },
  {
    name: "Gambian",
    value: "gambian",
    nationality_type: "gambian",
    telcode: "+1",
  },
  {
    name: "Georgian",
    value: "georgian",
    nationality_type: "georgian",
    telcode: "+1",
  },
  {
    name: "German",
    value: "german",
    nationality_type: "german",
    telcode: "+1",
  },
  {
    name: "Ghanaian",
    value: "ghanaian",
    nationality_type: "ghanaian",
    telcode: "+1",
  },
  {
    name: "Gibraltarian",
    value: "gibraltarian",
    nationality_type: "gibraltarian",
    telcode: "+1",
  },
  {
    name: "Greek",
    value: "greek",
    nationality_type: "greek",
    telcode: "+1",
  },
  {
    name: "Greenlandic",
    value: "greenlandic",
    nationality_type: "greenlandic",
    telcode: "+1",
  },
  {
    name: "Grenadian",
    value: "grenadian",
    nationality_type: "grenadian",
    telcode: "+1",
  },
  {
    name: "Guamanian",
    value: "guamanian",
    nationality_type: "guamanian",
    telcode: "+1",
  },
  {
    name: "Guatemalan",
    value: "guatemalan",
    nationality_type: "guatemalan",
    telcode: "+1",
  },
  {
    name: "Guinean",
    value: "guinean",
    nationality_type: "guinean",
    telcode: "+1",
  },
  {
    name: "Guyanese",
    value: "guyanese",
    nationality_type: "guyanese",
    telcode: "+1",
  },
  {
    name: "Haitian",
    value: "haitian",
    nationality_type: "haitian",
    telcode: "+1",
  },
  {
    name: "Honduran",
    value: "honduran",
    nationality_type: "honduran",
    telcode: "+1",
  },
  {
    name: "Hong Konger",
    value: "hong konger",
    nationality_type: "hong konger",
    telcode: "+1",
  },
  {
    name: "Hungarian",
    value: "hungarian",
    nationality_type: "hungarian",
    telcode: "+1",
  },
  {
    name: "Icelandic",
    value: "icelandic",
    nationality_type: "icelandic",
    telcode: "+1",
  },
  {
    name: "Indian",
    value: "indian",
    nationality_type: "indian",
    telcode: "+1",
  },
  {
    name: "Indonesian",
    value: "indonesian",
    nationality_type: "indonesian",
    telcode: "+1",
  },
  {
    name: "Iranian",
    value: "iranian",
    nationality_type: "iranian",
    telcode: "+1",
  },
  {
    name: "Iraqi",
    value: "iraqi",
    nationality_type: "iraqi",
    telcode: "+1",
  },
  {
    name: "Irish",
    value: "irish",
    nationality_type: "irish",
    telcode: "+1",
  },
  {
    name: "Israeli",
    value: "israeli",
    nationality_type: "israeli",
    telcode: "+1",
  },
  {
    name: "Italian",
    value: "italian",
    nationality_type: "italian",
    telcode: "+1",
  },
  {
    name: "Ivorian",
    value: "ivorian",
    nationality_type: "ivorian",
    telcode: "+1",
  },
  {
    name: "Jamaican",
    value: "jamaican",
    nationality_type: "jamaican",
    telcode: "+1",
  },
  {
    name: "Japanese",
    value: "japanese",
    nationality_type: "japanese",
    telcode: "+1",
  },
  {
    name: "Jordanian",
    value: "jordanian",
    nationality_type: "jordanian",
    telcode: "+1",
  },
  {
    name: "Kazakh",
    value: "kazakh",
    nationality_type: "kazakh",
    telcode: "+1",
  },
  {
    name: "Kenyan",
    value: "kenyan",
    nationality_type: "kenyan",
    telcode: "+1",
  },
  {
    name: "Kittitian",
    value: "kittitian",
    nationality_type: "kittitian",
    telcode: "+1",
  },
  {
    name: "Kosovan",
    value: "kosovan",
    nationality_type: "kosovan",
    telcode: "+1",
  },
  {
    name: "Kuwaiti",
    value: "kuwaiti",
    nationality_type: "kuwaiti",
    telcode: "+1",
  },
  {
    name: "Kyrgyz",
    value: "kyrgyz",
    nationality_type: "kyrgyz",
    telcode: "+1",
  },
  {
    name: "Lao",
    value: "lao",
    nationality_type: "lao",
    telcode: "+1",
  },
  {
    name: "Latvian",
    value: "latvian",
    nationality_type: "latvian",
    telcode: "+1",
  },
  {
    name: "Lebanese",
    value: "lebanese",
    nationality_type: "lebanese",
    telcode: "+1",
  },
  {
    name: "Liberian",
    value: "liberian",
    nationality_type: "liberian",
    telcode: "+1",
  },
  {
    name: "Libyan",
    value: "libyan",
    nationality_type: "libyan",
    telcode: "+1",
  },
  {
    name: "Liechtenstein citizen",
    value: "liechtenstein citizen",
    nationality_type: "liechtenstein citizen",
    telcode: "+1",
  },
  {
    name: "Lithuanian",
    value: "lithuanian",
    nationality_type: "lithuanian",
    telcode: "+1",
  },
  {
    name: "Luxembourger",
    value: "luxembourger",
    nationality_type: "luxembourger",
    telcode: "+1",
  },
  {
    name: "Macanese",
    value: "macanese",
    nationality_type: "macanese",
    telcode: "+1",
  },
  {
    name: "Macedonian",
    value: "macedonian",
    nationality_type: "macedonian",
    telcode: "+1",
  },
  {
    name: "Malagasy",
    value: "malagasy",
    nationality_type: "malagasy",
    telcode: "+1",
  },
  {
    name: "Malawian",
    value: "malawian",
    nationality_type: "malawian",
    telcode: "+1",
  },
  {
    name: "Malaysian",
    value: "malaysian",
    nationality_type: "malaysian",
    telcode: "+1",
  },
  {
    name: "Maldivian",
    value: "maldivian",
    nationality_type: "maldivian",
    telcode: "+1",
  },
  {
    name: "Malian",
    value: "malian",
    nationality_type: "malian",
    telcode: "+1",
  },
  {
    name: "Maltese",
    value: "maltese",
    nationality_type: "maltese",
    telcode: "+1",
  },
  {
    name: "Marshallese",
    value: "marshallese",
    nationality_type: "marshallese",
    telcode: "+1",
  },
  {
    name: "Martiniquais",
    value: "martiniquais",
    nationality_type: "martiniquais",
    telcode: "+1",
  },
  {
    name: "Mauritanian",
    value: "mauritanian",
    nationality_type: "mauritanian",
    telcode: "+1",
  },
  {
    name: "Mauritian",
    value: "mauritian",
    nationality_type: "mauritian",
    telcode: "+1",
  },
  {
    name: "Mexican",
    value: "mexican",
    nationality_type: "mexican",
    telcode: "+1",
  },
  {
    name: "Micronesian",
    value: "micronesian",
    nationality_type: "micronesian",
    telcode: "+1",
  },
  {
    name: "Moldovan",
    value: "moldovan",
    nationality_type: "moldovan",
    telcode: "+1",
  },
  {
    name: "Monegasque",
    value: "monegasque",
    nationality_type: "monegasque",
    telcode: "+1",
  },
  {
    name: "Mongolian",
    value: "mongolian",
    nationality_type: "mongolian",
    telcode: "+1",
  },
  {
    name: "Montenegrin",
    value: "montenegrin",
    nationality_type: "montenegrin",
    telcode: "+1",
  },
  {
    name: "Montserratian",
    value: "montserratian",
    nationality_type: "montserratian",
    telcode: "+1",
  },
  {
    name: "Moroccan",
    value: "moroccan",
    nationality_type: "moroccan",
    telcode: "+1",
  },
  {
    name: "Mosotho",
    value: "mosotho",
    nationality_type: "mosotho",
    telcode: "+1",
  },
  {
    name: "Mozambican",
    value: "mozambican",
    nationality_type: "mozambican",
    telcode: "+1",
  },
  {
    name: "Namibian",
    value: "namibian",
    nationality_type: "namibian",
    telcode: "+1",
  },
  {
    name: "Nauruan",
    value: "nauruan",
    nationality_type: "nauruan",
    telcode: "+1",
  },
  {
    name: "Nepalese",
    value: "nepalese",
    nationality_type: "nepalese",
    telcode: "+1",
  },
  {
    name: "New Zealander",
    value: "new zealander",
    nationality_type: "new zealander",
    telcode: "+1",
  },
  {
    name: "Nicaraguan",
    value: "nicaraguan",
    nationality_type: "nicaraguan",
    telcode: "+1",
  },
  {
    name: "Nigerian",
    value: "nigerian",
    nationality_type: "nigerian",
    telcode: "+1",
  },
  {
    name: "Nigerien",
    value: "nigerien",
    nationality_type: "nigerien",
    telcode: "+1",
  },
  {
    name: "Niuean",
    value: "niuean",
    nationality_type: "niuean",
    telcode: "+1",
  },
  {
    name: "North Korean",
    value: "north korean",
    nationality_type: "north korean",
    telcode: "+1",
  },
  {
    name: "Northern Irish",
    value: "northern irish",
    nationality_type: "northern irish",
    telcode: "+1",
  },
  {
    name: "Norwegian",
    value: "norwegian",
    nationality_type: "norwegian",
    telcode: "+1",
  },
  {
    name: "Omani",
    value: "omani",
    nationality_type: "omani",
    telcode: "+1",
  },
  {
    name: "Pakistani",
    value: "pakistani",
    nationality_type: "pakistani",
    telcode: "+1",
  },
  {
    name: "Palauan",
    value: "palauan",
    nationality_type: "palauan",
    telcode: "+1",
  },
  {
    name: "Palestinian",
    value: "palestinian",
    nationality_type: "palestinian",
    telcode: "+1",
  },
  {
    name: "Panamanian",
    value: "panamanian",
    nationality_type: "panamanian",
    telcode: "+1",
  },
  {
    name: "Papua New Guinean",
    value: "papua new guinean",
    nationality_type: "papua new guinean",
    telcode: "+1",
  },
  {
    name: "Paraguayan",
    value: "paraguayan",
    nationality_type: "paraguayan",
    telcode: "+1",
  },
  {
    name: "Peruvian",
    value: "peruvian",
    nationality_type: "peruvian",
    telcode: "+1",
  },
  {
    name: "Pitcairn Islander",
    value: "pitcairn islander",
    nationality_type: "pitcairn islander",
    telcode: "+1",
  },
  {
    name: "Polish",
    value: "polish",
    nationality_type: "polish",
    telcode: "+1",
  },
  {
    name: "Portuguese",
    value: "portuguese",
    nationality_type: "portuguese",
    telcode: "+1",
  },
  {
    name: "Prydeinig",
    value: "prydeinig",
    nationality_type: "prydeinig",
    telcode: "+1",
  },
  {
    name: "Puerto Rican",
    value: "puerto rican",
    nationality_type: "puerto rican",
    telcode: "+1",
  },
  {
    name: "Qatari",
    value: "qatari",
    nationality_type: "qatari",
    telcode: "+1",
  },
  {
    name: "Romanian",
    value: "romanian",
    nationality_type: "romanian",
    telcode: "+1",
  },
  {
    name: "Russian",
    value: "russian",
    nationality_type: "russian",
    telcode: "+1",
  },
  {
    name: "Rwandan",
    value: "rwandan",
    nationality_type: "rwandan",
    telcode: "+1",
  },
  {
    name: "Salvadorean",
    value: "salvadorean",
    nationality_type: "salvadorean",
    telcode: "+1",
  },
  {
    name: "Sammarinese",
    value: "sammarinese",
    nationality_type: "sammarinese",
    telcode: "+1",
  },
  {
    name: "Samoan",
    value: "samoan",
    nationality_type: "samoan",
    telcode: "+1",
  },
  {
    name: "Sao Tomean",
    value: "sao tomean",
    nationality_type: "sao tomean",
    telcode: "+1",
  },
  {
    name: "Saudi Arabian",
    value: "saudi arabian",
    nationality_type: "saudi arabian",
    telcode: "+1",
  },
  {
    name: "Scottish",
    value: "scottish",
    nationality_type: "scottish",
    telcode: "+1",
  },
  {
    name: "Senegalese",
    value: "senegalese",
    nationality_type: "senegalese",
    telcode: "+1",
  },
  {
    name: "Serbian",
    value: "serbian",
    nationality_type: "serbian",
    telcode: "+1",
  },
  {
    name: "Sierra Leonean",
    value: "sierra leonean",
    nationality_type: "sierra leonean",
    telcode: "+1",
  },
  {
    name: "Singaporean",
    value: "singaporean",
    nationality_type: "singaporean",
    telcode: "+1",
  },
  {
    name: "Slovak",
    value: "slovak",
    nationality_type: "slovak",
    telcode: "+1",
  },
  {
    name: "Slovenian",
    value: "slovenian",
    nationality_type: "slovenian",
    telcode: "+1",
  },
  {
    name: "Solomon Islander",
    value: "solomon islander",
    nationality_type: "solomon islander",
    telcode: "+1",
  },
  {
    name: "Somali",
    value: "somali",
    nationality_type: "somali",
    telcode: "+1",
  },
  {
    name: "South African",
    value: "south african",
    nationality_type: "south african",
    telcode: "+1",
  },
  {
    name: "South Korean",
    value: "south korean",
    nationality_type: "south korean",
    telcode: "+1",
  },
  {
    name: "South Sudanese",
    value: "south sudanese",
    nationality_type: "south sudanese",
    telcode: "+1",
  },
  {
    name: "Spanish",
    value: "spanish",
    nationality_type: "spanish",
    telcode: "+1",
  },
  {
    name: "Sri Lankan",
    value: "sri lankan",
    nationality_type: "sri lankan",
    telcode: "+1",
  },
  {
    name: "St Helenian",
    value: "st helenian",
    nationality_type: "st helenian",
    telcode: "+1",
  },
  {
    name: "St Lucian",
    value: "st lucian",
    nationality_type: "st lucian",
    telcode: "+1",
  },
  {
    name: "Stateless",
    value: "stateless",
    nationality_type: "stateless",
    telcode: "+1",
  },
  {
    name: "Sudanese",
    value: "sudanese",
    nationality_type: "sudanese",
    telcode: "+1",
  },
  {
    name: "Surinamese",
    value: "surinamese",
    nationality_type: "surinamese",
    telcode: "+1",
  },
  {
    name: "Swazi",
    value: "swazi",
    nationality_type: "swazi",
    telcode: "+1",
  },
  {
    name: "Swedish",
    value: "swedish",
    nationality_type: "swedish",
    telcode: "+1",
  },
  {
    name: "Swiss",
    value: "swiss",
    nationality_type: "swiss",
    telcode: "+1",
  },
  {
    name: "Syrian",
    value: "syrian",
    nationality_type: "syrian",
    telcode: "+1",
  },
  {
    name: "Taiwanese",
    value: "taiwanese",
    nationality_type: "taiwanese",
    telcode: "+1",
  },
  {
    name: "Tajik",
    value: "tajik",
    nationality_type: "tajik",
    telcode: "+1",
  },
  {
    name: "Tanzanian",
    value: "tanzanian",
    nationality_type: "tanzanian",
    telcode: "+1",
  },
  {
    name: "Thai",
    value: "thai",
    nationality_type: "thai",
    telcode: "+1",
  },
  {
    name: "Togolese",
    value: "togolese",
    nationality_type: "togolese",
    telcode: "+1",
  },
  {
    name: "Tongan",
    value: "tongan",
    nationality_type: "tongan",
    telcode: "+1",
  },
  {
    name: "Trinidadian",
    value: "trinidadian",
    nationality_type: "trinidadian",
    telcode: "+1",
  },
  {
    name: "Tristanian",
    value: "tristanian",
    nationality_type: "tristanian",
    telcode: "+1",
  },
  {
    name: "Tunisian",
    value: "tunisian",
    nationality_type: "tunisian",
    telcode: "+1",
  },
  {
    name: "Turkish",
    value: "turkish",
    nationality_type: "turkish",
    telcode: "+1",
  },
  {
    name: "Turkmen",
    value: "turkmen",
    nationality_type: "turkmen",
    telcode: "+1",
  },
  {
    name: "Turks and Caicos Islander",
    value: "turks and caicos islander",
    nationality_type: "turks and caicos islander",
    telcode: "+1",
  },
  {
    name: "Tuvaluan",
    value: "tuvaluan",
    nationality_type: "tuvaluan",
    telcode: "+1",
  },
  {
    name: "Ugandan",
    value: "ugandan",
    nationality_type: "ugandan",
    telcode: "+1",
  },
  {
    name: "Ukrainian",
    value: "ukrainian",
    nationality_type: "ukrainian",
    telcode: "+1",
  },
  {
    name: "Uruguayan",
    value: "uruguayan",
    nationality_type: "uruguayan",
    telcode: "+1",
  },
  {
    name: "Uzbek",
    value: "uzbek",
    nationality_type: "uzbek",
    telcode: "+1",
  },
  {
    name: "Vatican citizen",
    value: "vatican citizen",
    nationality_type: "vatican citizen",
    telcode: "+1",
  },
  {
    name: "Venezuelan",
    value: "venezuelan",
    nationality_type: "venezuelan",
    telcode: "+1",
  },
  {
    name: "Vietnamese",
    value: "vietnamese",
    nationality_type: "vietnamese",
    telcode: "+1",
  },
  {
    name: "Vincentian",
    value: "vincentian",
    nationality_type: "vincentian",
    telcode: "+1",
  },
  {
    name: "Wallisian",
    value: "wallisian",
    nationality_type: "wallisian",
    telcode: "+1",
  },
  {
    name: "Welsh",
    value: "welsh",
    nationality_type: "welsh",
    telcode: "+1",
  },
  {
    name: "Yemeni",
    value: "yemeni",
    nationality_type: "yemeni",
    telcode: "+1",
  },
  {
    name: "Zambian",
    value: "zambian",
    nationality_type: "zambian",
    telcode: "+1",
  },
  {
    name: "Zimbabwean",
    value: "zimbabwean",
    nationality_type: "zimbabwean",
    telcode: "+1",
  },
];

export const REGIONS: { name: string; value: string; id?: string }[] = [
  { name: "Ahafo region", value: "ahafo region" },
  { name: "Ashanti region", value: "ashanti region" },
  { name: "Bono East region", value: "bono east region" },
  { name: "Bono region", value: "bono region" },
  { name: "Central region", value: "central region" },
  { name: "Eastern region", value: "eastern region" },
  { name: "Greater Accra region", value: "greater accra region" },
  {
    name: "North East region",
    value: "north east region",
  },
  { name: "Northern region", value: "northern region" },
  { name: "Oti region", value: "oti region" },
  { name: "Savannah region", value: "savannah region" },
  { name: "Upper east region", value: "upper east region" },
  { name: "Upper west region", value: "upper west region" },
  { name: "volta region", value: "volta region" },
  { name: "Western north region", value: "western north region" },
  { name: "Western region", value: "western region" },
  { name: "Outside Ghana", value: "outside ghana" },
];
